[project]
name = "librarymcp"
version = "0.1.0"
description = "Library backend server to serve MCP tool invokation"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.0",
    "uvicorn>=0.41.0",
]
